import QtQuick

QtObject {
    property IconData priorityHigh
    property IconData pause
    property IconData logo
    property IconData accountBalance
    property IconData accountBox
    property IconData accountCircle
    property IconData adb
    property IconData add
    property IconData addAPhoto
    property IconData addBox
    property IconData addBusiness
    property IconData addCard
    property IconData addCircle
    property IconData addPhotoAlternate
    property IconData addShoppingCart
    property IconData air
    property IconData alarm
    property IconData analytics
    property IconData android
    property IconData apps
    property IconData arrowBack
    property IconData arrowDownward
    property IconData arrowDropDown
    property IconData arrowDropUp
    property IconData arrowForward
    property IconData arrowRight
    property IconData atr
    property IconData attachMoney
    property IconData autorenew
    property IconData backspace
    property IconData badge
    property IconData barChart
    property IconData barcodeScanner
    property IconData batteryChargingFull
    property IconData batteryFull
    property IconData batteryFullAlt
    property IconData bluetooth
    property IconData bookmark
    property IconData brush
    property IconData build
    property IconData cable
    property IconData cake
    property IconData calculate
    property IconData calendarMonth
    property IconData calendarToday
    property IconData call
    property IconData camera
    property IconData campaign
    property IconData cancel
    property IconData cast
    property IconData category
    property IconData celebration
    property IconData chat
    property IconData chatBubble
    property IconData check
    property IconData checkBox
    property IconData checkBoxOutlineBlank
    property IconData checkCircle
    property IconData chevronLeft
    property IconData chevronRight
    property IconData circle
    property IconData close
    property IconData code
    property IconData computer
    property IconData construction
    property IconData contactSupport
    property IconData contentCopy
    property IconData creditCard
    property IconData cropFree
    property IconData currencyBitcoin
    property IconData darkMode
    property IconData dashboard
    property IconData database
    property IconData deleteElement
    property IconData deleteForever
    property IconData description
    property IconData devices
    property IconData directionsCar
    property IconData domain
    property IconData doneAll
    property IconData download
    property IconData downloadForOffline
    property IconData draw
    property IconData eco
    property IconData edit
    property IconData editNote
    property IconData electricBolt
    property IconData emojiObjects
    property IconData engineering
    property IconData error
    property IconData euro
    property IconData event
    property IconData explore
    property IconData extension
    property IconData familiarFaceAndZone
    property IconData fastForward
    property IconData fastRewind
    property IconData favorite
    property IconData fileCopy
    property IconData filterAlt
    property IconData filterList
    property IconData finance
    property IconData fingerprint
    property IconData flag
    property IconData flashOn
    property IconData flashlightOn
    property IconData flight
    property IconData folder
    property IconData folderOpen
    property IconData forum
    property IconData gridOn
    property IconData gridView
    property IconData group
    property IconData groupAdd
    property IconData groups
    property IconData handyman
    property IconData headphones
    property IconData hearing
    property IconData help
    property IconData history
    property IconData home
    property IconData homePin
    property IconData image
    property IconData imagesmode
    property IconData info
    property IconData inventory
    property IconData inventory2
    property IconData keyboardArrowDown
    property IconData keyboardArrowLeft
    property IconData keyboardArrowRight
    property IconData keyboardArrowUp
    property IconData label
    property IconData landscape
    property IconData language
    property IconData leaderboard
    property IconData lightMode
    property IconData lightbulb
    property IconData link
    property IconData list
    property IconData localCafe
    property IconData localMall
    property IconData locationOn
    property IconData lock
    property IconData lockOpen
    property IconData login
    property IconData logout
    property IconData loyalty
    property IconData mail
    property IconData manageAccounts
    property IconData map
    property IconData menu
    property IconData mic
    property IconData modeComment
    property IconData monitoring
    property IconData moreHoriz
    property IconData moreVert
    property IconData movie
    property IconData musicNote
    property IconData myLocation
    property IconData navigation
    property IconData nearMe
    property IconData nestEcoLeaf
    property IconData nestRemoteComfortSensor
    property IconData nightlight
    property IconData notifications
    property IconData openInNew
    property IconData paid
    property IconData palette
    property IconData pauseCircle
    property IconData person
    property IconData personAdd
    property IconData personPin
    property IconData pets
    property IconData phoneIphone
    property IconData photoCamera
    property IconData photoLibrary
    property IconData pictureAsPdf
    property IconData pinDrop
    property IconData playArrow
    property IconData playCircle
    property IconData power
    property IconData printElement
    property IconData publicElement
    property IconData qrCode
    property IconData qrCode2
    property IconData qrCodeScanner
    property IconData queryStats
    property IconData questionMark
    property IconData radar
    property IconData refresh
    property IconData remove
    property IconData repeat
    property IconData replay
    property IconData report
    property IconData restartAlt
    property IconData restaurant
    property IconData restaurantMenu
    property IconData rocketLaunch
    property IconData rssFeed
    property IconData save
    property IconData savings
    property IconData schedule
    property IconData school
    property IconData science
    property IconData search
    property IconData security
    property IconData sell
    property IconData send
    property IconData settings
    property IconData share
    property IconData shoppingBag
    property IconData shoppingCart
    property IconData shuffle
    property IconData signalCellularAlt
    property IconData skipNext
    property IconData skipPrevious
    property IconData smartphone
    property IconData sort
    property IconData sportsEsports
    property IconData sportsSoccer
    property IconData stadiaController
    property IconData star
    property IconData stop
    property IconData stopCircle
    property IconData storage
    property IconData store
    property IconData storefront
    property IconData subscriptions
    property IconData sync
    property IconData taskAlt
    property IconData theaters
    property IconData thumbUp
    property IconData timeline
    property IconData timer
    property IconData touchApp
    property IconData trendingDown
    property IconData trendingUp
    property IconData tune
    property IconData undo
    property IconData update
    property IconData uploadFile
    property IconData usb
    property IconData verified
    property IconData verifiedUser
    property IconData videoLibrary
    property IconData videocam
    property IconData visibility
    property IconData visibilityOff
    property IconData volumeOff
    property IconData volumeUp
    property IconData wallet
    property IconData wallpaper
    property IconData warning
    property IconData wbSunny
    property IconData whereToVote
    property IconData widgets
    property IconData wifi
    property IconData wifiOff
    property IconData work
    property IconData dashedCircle
    property IconData colorize


    function getAll() : list<string> {
        return _root.getPropertyNames(this);
    }
}
